from .decorators import addGAttr
from .tableConfig import setCarsTableAndInputConfig, setCarsWithViewEditLinksTableAndInputConfig, setEmployeesTableConfig, setItemsTableAndInputConfig, setWorkEffortsByCarWithEmployeesTableAndInputConfig
from .tableConfig import columnWebAttributes, columnNamesAndAttributes, VisibilityOptions, InputTypes